-- Новые поля профиля для участников
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS education TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS workplace VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS position VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pd_consent BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pd_consent_at TIMESTAMP;

-- Новые поля профиля для экспертов
ALTER TABLE experts ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE experts ADD COLUMN IF NOT EXISTS education TEXT;
ALTER TABLE experts ADD COLUMN IF NOT EXISTS workplace VARCHAR(255);
ALTER TABLE experts ADD COLUMN IF NOT EXISTS position VARCHAR(255);
ALTER TABLE experts ADD COLUMN IF NOT EXISTS city VARCHAR(255);
ALTER TABLE experts ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE experts ADD COLUMN IF NOT EXISTS pd_consent BOOLEAN DEFAULT FALSE;
ALTER TABLE experts ADD COLUMN IF NOT EXISTS pd_consent_at TIMESTAMP;